In [1]:
import numpy as np

In [2]:
def align(s1, s2, match=1, gap_penalty=1, mismatch_penalty=1):
    
    M = np.zeros([len(s1) + 1, len(s2) + 1], int)              
    route = {}
        
    for i in range(1, len(s1) + 1):
        for j in range(1, len(s2) + 1):
            
            # first calculate the score and generate the matrix 
            if s1[i - 1] == s2[j - 1]:
                # when match, add the score of match
                ul = M[i - 1, j - 1] + match 
            else:
                # when miss the match, minus the score of mismatch penalty
                ul = M[i - 1, j - 1] - mismatch_penalty 
            # there are two possibility to generate gaps:
            u = M[i - 1, j] - gap_penalty  # when theres insertion in the DNA sequence
            l = M[i, j - 1] - gap_penalty  # when theres deletion in the DNA sequence
            
            # get the score for each element in this matrix
            M[i, j] = max(ul, u, l, 0)
            
            # set the key of path as a list with the location of each element in M
            index = '[' + str(i) + ', ' + str(j) + ']'
            route[index] = []
            
            if ul == M[i, j]:
                route[index].append('[' + str(i - 1) + ', ' + str(j - 1) + ']')             
            if u == M[i, j]:
                route[index].append('[' + str(i - 1) + ', ' + str(j) + ']')
            if l == M[i, j]: 
                route[index].append('[' + str(i) + ', ' + str(j - 1) + ']')  
            
    max_index = np.argwhere(M == M.max()) 
    
    print("Matrix = ")
    print(M)
    # the score indicates the max value in the matrix 
    print("score = " + str(M.max()))
    
    for i in range(0, len(s1) + 1):
        route["[" + str(i) + ', 0]'] = []

    for i in range(0, len(s2) + 1):
        route['[0, ' + str(i) + "]"] = []
    
    #print(max_index)
    
    # set a for loop since there might be multiple M.max()
    for i in max_index: #traceback to find the route
        tb = route[str(list(i))]
        route_result = [str(list(i))]
      
        traceback(s1, s2, route, M, tb, route_result)
        #print(value)
        #print(route_result)

In [11]:
def traceback(s1,s2, route, M, tb, route_result):
    
    # append the value
    if tb != []:    
        i = (tb[0].split(',')[0])
        j = (tb[0].split(',')[1])
        i = int(i.strip('['))
        j = int(j.strip(']'))
        
        route_result.append(tb[0])
        tb = route[tb[0]]
    
    # recursively call function traceback when the value is not 0    
    if M[i, j] != 0:
        traceback(s1, s2, route, M, tb, route_result)
    else:
        right = 0
        down = 0
        seq1 = ''
        seq2 = ''
        for n in range(len(route_result)-2, -1, -1):
            location = route_result[n]
            
            i = (location.split(',')[0])
            j = (location.split(',')[1])
            i = int(i.strip('['))
            j = int(j.strip(']'))
        
            # deletion
            if j == down:
                seq1 += s1[i-1]
                seq2 += '-'
                
            # insertion
            elif i == right:
                seq1 += '-'
                seq2 += s2[j-1]
            
    
            # match
            else:
                seq1 += s1[i-1]
                seq2 += s2[j-1]
                
            right = i
            down = j     
            
        print("seq1 ="+ str(seq1))
        print("seq2 ="+ str(seq2))

In [12]:
align('tgcatcgagaccctacgtgac', 'actagacctagcatcgac')

Matrix = 
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 1 0 0 0 2 1 0 1 0 0 1]
 [0 1 0 0 1 0 1 0 0 0 1 0 1 3 2 1 0 1 0]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 2 4 3 2 1 0]
 [0 0 1 0 0 0 0 1 1 0 0 0 1 1 3 5 4 3 2]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 2 4 6 5 4]
 [0 1 0 0 1 0 2 1 0 0 1 0 0 1 1 3 5 7 6]
 [0 0 0 0 0 2 1 1 0 0 0 2 1 0 0 2 4 6 6]
 [0 1 0 0 1 1 3 2 1 0 1 1 1 2 1 1 3 5 5]
 [0 0 2 1 0 0 2 4 3 2 1 0 2 1 1 2 2 4 6]
 [0 0 1 1 0 0 1 3 5 4 3 2 1 1 0 2 1 3 5]
 [0 0 1 0 0 0 0 2 4 4 3 2 3 2 1 1 1 2 4]
 [0 0 0 2 1 0 0 1 3 5 4 3 2 2 3 2 1 1 3]
 [0 1 0 1 3 2 1 0 2 4 6 5 4 3 2 2 1 2 2]
 [0 0 2 1 2 2 1 2 1 3 5 5 6 5 4 3 2 1 3]
 [0 0 1 1 1 3 2 1 1 2 4 6 5 5 4 3 4 3 2]
 [0 0 0 2 1 2 2 1 0 2 3 5 5 4 6 5 4 3 2]
 [0 0 0 1 1 2 1 1 0 1 2 4 4 4 5 5 6 5 4]
 [0 1 0 0 2 1 3 2 1 0 2 3 3 5 4 4 5 7 6]
 [0 0 2 1 1 1 2 4 3 2 1 2 4 4 4 5 4 6 8]]
score = 8
seq1 =agacccta-cgt-gac
seq2 =aga-cctagcatcgac


In [13]:
align('tgcatcgagaccctacgtgac', 'actagacctagcatcgac', gap_penalty=2)

Matrix = 
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 1 0 0 0 2 0 0 1 0 0 1]
 [0 1 0 0 1 0 1 0 0 0 1 0 0 3 1 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 1 4 2 0 0 0]
 [0 0 1 0 0 0 0 1 1 0 0 0 1 0 2 5 3 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 3 6 4 2]
 [0 1 0 0 1 0 2 0 0 0 1 0 0 1 0 1 4 7 5]
 [0 0 0 0 0 2 0 1 0 0 0 2 0 0 0 0 2 5 6]
 [0 1 0 0 1 0 3 1 0 0 1 0 1 1 0 0 0 3 4]
 [0 0 2 0 0 0 1 4 2 0 0 0 1 0 0 1 0 1 4]
 [0 0 1 1 0 0 0 2 5 3 1 0 1 0 0 1 0 0 2]
 [0 0 1 0 0 0 0 1 3 4 2 0 1 0 0 1 0 0 1]
 [0 0 0 2 0 0 0 0 1 4 3 1 0 0 1 0 0 0 0]
 [0 1 0 0 3 1 1 0 0 2 5 3 1 1 0 0 0 1 0]
 [0 0 2 0 1 2 0 2 1 0 3 4 4 2 0 1 0 0 2]
 [0 0 0 1 0 2 1 0 1 0 1 4 3 3 1 0 2 0 0]
 [0 0 0 1 0 0 1 0 0 2 0 2 3 2 4 2 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 1 1 1 2 2 3 3 1 0]
 [0 1 0 0 1 0 2 0 0 0 1 0 0 2 1 1 2 4 2]
 [0 0 2 0 0 0 0 3 1 0 0 0 1 0 1 2 0 2 5]]
score = 7
seq1 =gcatcga
seq2 =gcatcga


In [14]:
align('tgcatcgagaccctacgtgac', 'actagacctagcatcgac', match = 3, gap_penalty=2, mismatch_penalty = 3)

Matrix = 
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  1  0  0  0  0  3  1  0  0  0  3  1  0  0  0]
 [ 0  0  0  1  0  4  2  0  0  1  0  4  2  0  1  0  4  2  0]
 [ 0  0  3  1  0  2  1  5  3  1  0  2  7  5  3  4  2  1  5]
 [ 0  3  1  0  4  2  5  3  2  0  4  2  5 10  8  6  4  5  3]
 [ 0  1  0  4  2  1  3  2  0  5  3  1  3  8 13 11  9  7  5]
 [ 0  0  4  2  1  0  1  6  5  3  2  0  4  6 11 16 14 12 10]
 [ 0  0  2  1  0  4  2  4  3  2  0  5  3  4  9 14 19 17 15]
 [ 0  3  1  0  4  2  7  5  3  1  5  3  2  6  7 12 17 22 20]
 [ 0  1  0  0  2  7  5  4  2  0  3  8  6  4  5 10 15 20 19]
 [ 0  3  1  0  3  5 10  8  6  4  3  6  5  9  7  8 13 18 17]
 [ 0  1  6  4  2  3  8 13 11  9  7  5  9  7  6 10 11 16 21]
 [ 0  0  4  3  1  1  6 11 16 14 12 10  8  6  4  9  9 14 19]
 [ 0  0  3  1  0  0  4  9 14 13 11  9 13 11  9  7  7 12 17]
 [ 0  0  1  6  4  2  2  7 12 17 15 13 11 10 14 12 10 10 15]
 [ 0  3  1  4  9  7  5  5 10 15 20 18 16 14 12 11  9 13 13]
 [ 0  1  6  4  7  6  4  8  8 1